# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='icnonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('upload', models.FileField(upload_to='licencias/img/')),
            ],
        ),
    ]
